name: build-daily
on:
    workflow_dispatch: ~
    schedule:
        # Every day at 3am UTC
        - cron:  '0 3 * * *'

defaults:
    run:
        shell: bash

jobs:
    build-daily:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.PAT }}

            - name: Composer install
              uses: docker://jrmgx/wikireveal
              with:
                  args: composer install

            - name: Build
              uses: docker://jrmgx/wikireveal
              with:
                  args: bin/console app:build

            - name: Publish new Puzzle
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: New Puzzle of the day!
